columns: 80
newline: lf

language_extensions:
  - PatternSynonyms
  - TemplateHaskell

steps:

  - simple_align:
      cases: adjacent
      top_level_patterns: adjacent
      records: adjacent
      multi_way_if: adjacent

  - imports:
      align: group
      pad_module_names: false
      long_list_align: inline
      separate_lists: true
      space_surround: false

  - language_pragmas:
      style: compact
      align: false
      remove_redundant: true
      language_prefix: language

  - trailing_whitespace: {}
